name: singularity-deploy

on:
  push:
    branches: ["main"]
  repository_dispatch:
    types: [custom-event] 
  workflow_dispatch:

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 

      - uses: eWaterCycle/setup-apptainer@v2
        with:
          apptainer-version: 1.3.2

      - name: Create sif with apptainer
        run: |
          apptainer build --fakeroot image.sif image.def


      #- name: Upload .sif in an artifact
      #  uses: actions/upload-artifact@v3
      #  with:
      #    name: apptainer-image
      #    path: image.sif

      - name: Publish image to Zenodo
        env:
          ZENODO_TOKEN: ${{ secrets.ZENODO }}
        run: |
          # Define the deposition ID
          DEPOSITION_ID=13271931

          # Upload the new file to the existing record
          echo "Uploading image to existing Zenodo record..."
          curl -s -X POST "https://zenodo.org/api/deposit/depositions/$DEPOSITION_ID/files" \
            -H "Authorization: Bearer $ZENODO_TOKEN" \
            -F file=@image.sif


      - name: Publish updated Zenodo record
        env:
          ZENODO_TOKEN: ${{ secrets.ZENODO }}
        run: |
          DEPOSITION_ID=13271931
          echo "Publishing updated Zenodo record..."
          RESPONSE=$(curl -s -o response.json -w "%{http_code}" -X POST "https://zenodo.org/api/deposit/depositions/$DEPOSITION_ID/actions/publish" \
            -H "Authorization: Bearer $ZENODO_TOKEN")
          if [ "$RESPONSE" -ne 202 ]; then
            echo "Error publishing record: $(cat response.json)"
            exit 1
          fi
          echo "Zenodo record updated and published successfully."

