name: singularity-deploy

on:
  push:
    branches: ["main"]
  repository_dispatch:
    types: [custom-event] 
  workflow_dispatch:

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install apptainer
        run: |
          sudo apt-get install -y curl rpm2cpio cpio
          curl -s https://raw.githubusercontent.com/apptainer/apptainer/main/tools/install-unprivileged.sh | bash -s - install-dir


      - name: Create sif with apptainer
        run: |
          install-dir/bin/apptainer build image.sif image.def docker://mambaorg/micromamba:alpine

