name: singularity-deploy

on:
  push:
    branches: ["main"]
  repository_dispatch:
    types: [custom-event] 
  workflow_dispatch:

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install apptainer
        run: |
          sudo apt-get install -y curl rpm2cpio cpio
          curl -s https://raw.githubusercontent.com/apptainer/apptainer/main/tools/install-unprivileged.sh | bash -s - install-dir

#sudo install-dir/bin/apptainer config fakeroot --add $HOME
      - name: Create sif with apptainer
        run: |
          sudo chmod -R ugo+rwx install.sh
          install-dir/bin/apptainer build --fix-perms --sandbox /tmp/container.sif image.def

      - name: Upload .sif in an artifact
        uses: actions/upload-artifact@v3
        with:
          name: apptainer-image
          path: /tmp/container.sif
        

