name: singularity-deploy

on:
  push:
    branches: ["main"]
  repository_dispatch:
    types: [custom-event] 
  workflow_dispatch:

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 

      - uses: eWaterCycle/setup-apptainer@v2
        with:
          apptainer-version: 1.3.2

      - name: Create sif with apptainer
        run: |
          apptainer build --fakeroot image.sif image.def


      #- name: Upload .sif in an artifact
      #  uses: actions/upload-artifact@v3
      #  with:
      #    name: apptainer-image
      #    path: image.sif

      - name: publish on zenodo
        env:
          ZENODO_TOKEN: ${{ secrets.ZENODO }}
        run: |
          # Install 'requests' module for python
          pip install requests

          python zenodo_uploader.py \
          -z 13271931 \
          -T "Stockage for apptainer's pictures" \
          -C "Festor Quentin" \
          -A "Université de Montpellier" \  
          -D "Etude du stockage d'environnements apptainer créés sur github pour la reproductibilité scientifique en statistiques." \
          -x \
          image.sif


