name: singularity-deploy

on:
  push:
    branches: ["main"]
  repository_dispatch:
    types: [custom-event] 
  workflow_dispatch:

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: eWaterCycle/setup-apptainer@v2
        with:
          apptainer-version: 1.3.2

#sudo install-dir/bin/apptainer config fakeroot --add $HOME
      - name: Create sif with apptainer
        run: |
          apptainer build --fakeroot image.sif image.def


      - name: Upload .sif in an artifact
        uses: actions/upload-artifact@v3
        with:
          name: apptainer-image
          path: image.sif
        

