name: singularity-deploy

on:
  push:
    branches: ["main"]
  repository_dispatch:
    types: [custom-event] 
  workflow_dispatch:

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: eWaterCycle/setup-apptainer@v2
        with:
          apptainer-version: 1.3.2
        
      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.0'

      - name: Install R Dependencies with renv
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1

      - name: Create sif with apptainer
        run: |
          apptainer build --fakeroot image_r.sif image_r.def

      - name: Upload .sif in an artifact
        uses: actions/upload-artifact@v3
        with:
          name: apptainer-image
          path: image_r.sif
        

